ProfilPerusahaan/urls.py
from django.conf.urls import url
from .views import index, profil_perusahaan

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^profil_perusahaan/$', profil_perusahaan, name = 'profil_perusahaan')
]

fitur_forum/urls.py
from django.conf.urls import url
from .views import index, add_forum

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_forum', add_forum, name='add_forum'),
]

fitur_login/urls.py
from django.conf.urls import url
from .views import index,add_session,remove_session,add_company

urlpatterns = [
     url(r'^$', index, name='index'),
     url(r'^add-session/$', add_session, name='add-session'),
     url(r'^remove-session/$', remove_session, name='remove-session'),
     url(r'^add-company/$', add_company, name='add-company'),
     ]

tp2ppw/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import fitur_login.urls as fitur_login
import ProfilPerusahaan.urls as ProfilPerusahaan
import fitur_forum.urls as fitur_forum
from django.views.generic.base import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/fitur-login/', permanent=True), name='login'),
    url(r'^fitur-login/', include(fitur_login, namespace='fitur-login')),
    url(r'^profil-perusahaan/', include(ProfilPerusahaan, namespace='profil-perusahaan')),
    url(r'^fitur-forum/', include(fitur_forum, namespace='forum')),
]

ProfilPerusahaan/models.py
from django.db import models

# Create your models here.

fitur_forum/models.py
from django.db import models

class Forum(models.Model):
    #perusahaan = models.ForeignKey(Perusahaan)
    lowongan = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

fitur_login/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    id = models.CharField('id', max_length=20, primary_key=True, )
    name = models.CharField('Name', max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

fitur_forum/forms.py
from django import forms

class Forum_Lowongan(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    lowongan_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Masukan deskripsi...'
    }

    lowongan = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=lowongan_attrs))

ProfilPerusahaan/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
# Create your views here.
response = {}

# Create your views here.

def index(request):
    print ("#==> masuk index")
    if 'user_login' in request.session:
        return HttpResponseRedirect(reverse('profil-perusahaan:profil_perusahaan'))
    else:
        html = 'daftar_login.html'
        return render(request, html, response)


def profil_perusahaan(request):
    print ("#==> profile")
    ## sol : bagaimana cara mencegah error, jika url profile langsung diakses
    if 'user_login' not in request.session.keys():
        return HttpResponseRedirect(reverse('profil-perusahaan:index'))
    ## end of sol
    html = 'profil-perusahaan.html'
    return render(request, html, response)

fitur_forum/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Forum_Lowongan
from .models import Forum
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.
response = {}
def index(request):
    forum = Forum.objects.all().order_by('-created_date')
    
    #pagination
    paginator = Paginator(forum, 3)
    page = request.GET.get('page')
    try:
        halaman = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        halaman = paginator.page(1)


    response['Forum'] = halaman
    html = 'fitur_forum/fitur_forum.html'
    response['Forum_Lowongan'] = Forum_Lowongan
    return render(request, html, response)

def add_forum(request):
    form = Forum_Lowongan(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['lowongan'] = request.POST['lowongan']
        forum = Forum(lowongan=response['lowongan'])
        forum.save()
        return HttpResponseRedirect('/fitur-forum/')
    else:
        return HttpResponseRedirect('/fitur-forum/')

fitur_login/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from .models import User
from fitur_forum.models import Forum
# Create your views here.
response={}
def index(request):
    response['author'] = "Valerysa Regita" #TODO Implement yourname
    html = 'daftar_login.html'
    print(User.objects.all().values_list('name', flat=True) )
    response['forum']=Forum.objects.all()
    return render(request, html, response)

def add_session(request):
    if request.method == 'POST':
        name = request.POST['name']
        id = request.POST['id']
        request.session['user_login'] = id
        request.session['name'] = name
        try:
            user = User.objects.get(id = id)
        except Exception as e:
            user = User()
            user.id = id
            user.name = name
            user.save()
        return HttpResponseRedirect(reverse('fitur-login:index'))

def remove_session(request):
    request.session.flush()
    return HttpResponseRedirect(reverse('fitur-login:index'))

def add_company(request):
    if request.method == 'POST':
        company_name = request.POST['name']
        id = request.POST['id']
        request.session['company_login'] = id
        request.session['company_name'] = company_name
        return HttpResponseRedirect(reverse('fitur-login:index'))

ProfilPerusahaan/templates/profil-perusahaan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="TUGAS 2">
    <meta name="author" content="{{author}}">

    <!-- Bootstrap CSS -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- JQuery dataTables CSS -->
    <link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
<script type="text/javascript" src="//platform.linkedin.com/in.js">
    api_key: 81ilzph0rmtmjl	
    authorize: true
    onLoad: getID
</script>
    <style>
        
    </style>
    <title>
        {% block title %} Profil Perusahaan {% endblock %}
    </title>
</head>
<body>
    <header>
        
    </header>
    <content>
        <div class="container">
			<div id='profil-perusahaan' style="margin-top: 5%"> 	
				<div class="container" style="align-content: center;">
				<section style="height: auto;">
				    <header class="masthead">
				      <div class="overlay">
				        <div class="container">
				          <h1 class="display-1 text-white">WELCOME</h1>
				          <h2 class="display-4 text-white" id="companyName"><center> <!--TODO--> <center></h2>
				            <br>
				            <p align = "center">
				            <img src=http://cliparting.com/wp-content/uploads/2016/11/Small-office-building-clipart-kid.jpg widht="200" height="200" align = "center">
				          </p>
				          <br>
				          <a href="{% url 'forum:index' %}" class="head-button"><center>Lihat Forum</center></a>
				          <a href="#" class="head-button"><center>            Cari Mahasiswa<center></a>
				        </div>
				      </div>
				    </header>

				    <div class="container" style="margin-top: 4%;" id="about-company-section">
				      <div class="row">
				        <div class="col-lg-11 col-md-11 col-sm-11 col-11 mx-auto">
				          <h2 id="title-about">About Company:</h2>
				          <div id="about"></div>
				          <br>
				          <div class="row">
				            <div class="col-lg-6 col-md-4 col-sm-4 col-4" id="judul-about">
				              <h5 id="about-company">Tipe Perusahaan</h5>
				              <h5 id="about-company">Web Perusahaan</h5>
				              <h5 id="about-company">Spesialitas</h5>
				            </div>
				            <div class="col-lg-6 col-md-8 col-sm-4 col-8">
				              <h5 id="companyType"> <!--TODO--> </h5>
				              <h5 id="companyWeb"> <!--TODO--> </h5>
				              <h5 id="companySpecialty"> <!--TODO--> </h5>
				            </div>
				          </div>
				        </div>
				      </div>
				    </div>
				  </section>
					</div>
			</div>

			<button class='btn btn-danger' onClick='logout()'>Logout</button>


        </div>
    </content>
    <footer>
        
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- JQuery dataTables Script -->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
</body>
</html>




{% block javascript %}
<script type="text/javascript">
	
function getID(result){
	IN.API.Raw("companies?format=json&is-company-admin=true")
		.method("GET")
		.result(function(result){
			var id = result.values[0].id;
			console.log(id);
			getData(id);
		})
		.error(function(result){alert("haha");
		});	
}

function getData(result){
	IN.API.Raw("companies/"+result+":(company-type,website-url,specialties,name,ticker,description)?format=json")
		.method("GET")
		.result(function(result){
			  $("#companyName").append(result.name );
			  $("#companyType").append(result.companyType.name );
			  $("#companyWeb").append(result.websiteUrl);
			  var spesiality = "";
			  for (var i = 0; i < result.specialties.values.length ; i++) {
			  	console.log(result.specialties.values[i]);
			  	spesiality += result.specialties.values[i]+","
			  }
			  var res = spesiality.substring(0,spesiality.length-1);
			  $("#companySpecialty").append(res);
			  // $("#companyName").append(result.name );
			  // $("#companyName").append(result.name );
			  // $("#companyName").append(result.name );
		});


}



function logout(){
    IN.User.logout(logoutYuk);
}
// Remove profile data from page
function logoutYuk(){
	window.location.assign("{% url 'fitur-login:index'%}")
  $.ajax({
      method: "GET",
      url: '{% url "fitur-login:remove-session" %}',

});
}

</script>
{% endblock %}

fitur_forum/templates/fitur_forum/fitur_forum.html
{% extends "layout/base.html" %} 
{% load staticfiles%} 

{% block style %}
<link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'css/fitur_forum.css' %}">
{% endblock %}


{% block content %}
<section>
    <h2 class="forum-list-title"> Forum Lowongan Kerja</h2>
    <div class="container">
            {% if Forum %}
                {% for forum in Forum %}
                <div id = "forum post">
                    <h1> {{ forum.lowongan }}</h1>
                        <a style= "float: right;" id = "response" class= "btn btn-danger" href="#" onclick="test('{{ forum.id }}')"> Response</a>
                    <h5> {{ forum.created_date}}</h5>
                    <div id = "comments"></div>
                </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Maaf!</strong> Tidak ada forum
            </div>
            {% endif %}
        </div>


<div class="pagination">
    <span class="step-links">
        {% if Forum.has_previous %}
            <a href="?page={{ Forum.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ Forum.number }} of {{ Forum.paginator.num_pages }}.
        </span>

        {% if Forum.has_next %}
            <a href="?page={{ Forum.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
</section>

    <div id="myDiv">
    <input id="new_forum" class="btn btn-lg btn-block btn-info" value="Tambah Forum Lowongan" onclick="show()">
    </div>

    <div id="form" style="display:none" class="container">
      <form id="form" method="POST" action="{% url 'forum:add_forum' %}">
          <h2>Tambah Forum Lowongan Kerja</h2>
          {% csrf_token %}
          {{ Forum_Lowongan }}
          <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit" onclick="add()">
          <br>
      </form>
    </div>
    
    
    {% block javascript%}
    <script>
    function show(){

        var x = document.getElementById("form");
        
        if(x.style.display === "none"){
        x.style.display = "block";
        }else{
          x.style.display = "none";
        }
        $('#new_forum').hide();

        }

    function add(){
        var x = document.getElementById("form");
        
        if(x.style.display === "none"){
        x.style.display = "block";
        }else{
          x.style.display = "none";
        }
        $('#new_forum').show();
    }

    function test(id) {
        $("#comments").append("ntar disini form dengan ID " + id);
        $('#response').remove();
    }
    </script>
    {% endblock %}
    {% endblock %}
    

fitur_forum/templates/fitur_forum/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Login">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/b1_utama.css' %}" />
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title> Login</title>
</head>
<body>
    <header>
        {% include "b1_utama/partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>

    <!-- Jquery n Bootstrap Script -->
    <!-- <script src="{% static 'js/lab8.js' %}"></script> -->

    <!-- Script -->
    <script type="text/javascript" src="//platform.linkedin.com/in.js">
    api_key:   81kze45gb69r8f
    onLoad:    onLinkedInLoad
    authorize: true
    </script>
    <script src="{% static 'js/b1_utama.js' %}"></script>

</body>
</html>

fitur_login/templates/daftar_login.html
{% extends "layout/base.html" %}
{% block content %}
<center>
    <div id="lab8" >
        <script type="in/Login"></script>
    </div></center>
	<div id="profileData">
		<div id="name"></div>
		<div id="gambar"></div>
		<div id="tempat"></div>
	</div>
	<div id="logout">
<div class="panel panel-default" id=watch-later-{{movie.imdbid}}>
  <div class="panel-heading">
    <h3> LOWONGAN<h3>
  </div>
  <div class="panel-body">
    {% for a in forum %}
    <img class="img-circle" style="width:100px;height;100px"src='https://lh3.googleusercontent.com/-2WZh52QeErI/VmARDjn4d1I/AAAAAAAAAEQ/mDSvah2aOOE/w530-h476-n/Anjing-Lucu-2.jpg' style='height:50%;float: left;margin:2%' class='img-responsive img-thumbnail' id='gambar'/><br>
	<h4> Nama Perusahaan</h4>
	<h5> membuka lowongan kerja untuk : {{a.lowongan}} </h5>
	<h6> {{a.created_date}} </h6>
	{% endfor %}
</div>
  <div class="panel-footer">
</div>
</div>
	
	
	</div>
{% endblock %}

{% block javascript %}
<script>// Setup an event listener to make an API call once auth is complete
function onLinkedInLoad() {
    IN.Event.on(IN, "auth", getProfileData);
}

// Use the API call wrapper to request the member's profile data
function getProfileData() {
    IN.API.Profile("me").fields("id", "first-name", "last-name", "headline", "location", "picture-url", "public-profile-url", 
"email-address").result(displayProfileData).error(onError);

}

// Handle the successful return from the API call
function displayProfileData(data){
    var user = data.values[0];
	var id = user.id;
	console.log(id);
	$.ajax({
		method: "POST",
		url: '{% url "fitur-login:add-session" %}',
		data: { name: user.firstName+" "+user.lastName, id: id, csrfmiddlewaretoken: '{{ csrf_token }}'},
		success : function () {
		},
		error : function (error) {
          alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
		}
	});

    $("#name").append(user.firstName+' '+user.lastName+' '+user.headline );
	$("#gambar").append('<img src="'+user.pictureUrl+'">');
	$("#tempat").append(user.location.name);
	$("#logout").append("<button onClick='logout()'>Logout</button>");
	console.log(data);
	console.log();
	var url = "/companies?format=json&is-company-admin=true/";
	IN.API.Raw(url)
	.method("GET")
	.result(displayCompanyData)
	.error(onError);
}
function displayCompanyData(data){
    // To do
	console.log("jalan");
	cpnyID = data.values[0].id;
	IN.API.Raw("/companies/"+ cpnyID+":(id,name,ticker,description)?format=json")
	.method("GET")
	.result(print)
	.error(onError);
	console.log(data);
	    var user = data.values[0];

	  var id = user.id;
  console.log(id);
	console.log(user.name);
  $.ajax({
      method: "POST",
      url: '{% url "fitur-login:add-company" %}',
      data: { name: user.name, id: user.id, csrfmiddlewaretoken: '{{ csrf_token }}'},
      success : function () {
      },
      error : function (error) {
          alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
      }
  });

	
}
function print(data){
	console.log(data);
}

// Handle an error response from the API call
function onError(error) {
    console.log(error);
}

// Destroy the session of linkedin
function logout(){
    IN.User.logout(removeProfileData);
}

// Remove profile data from page
function removeProfileData(){
	window.location.assign("{% url 'fitur-login:index'%}")
}
</script>
{% endblock %}

tp2ppw/templates/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="TUGAS 2">
    <meta name="author" content="{{author}}">

    <!-- Bootstrap CSS -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- JQuery dataTables CSS -->
    <link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
    <!-- Own CSS -->
    <!-- <link href="{% static 'css/lab_10.css' %}" rel="stylesheet"> -->
<script type="text/javascript" src="//platform.linkedin.com/in.js">
    api_key: 81ilzph0rmtmjl	
    authorize: true
    onLoad: onLinkedInLoad
</script>
    <style>
        
    </style>
    <title>
        {% block title %} Tugas 2 PPW Kelompok Vale {% endblock %}
    </title>
</head>
<body>
    <header>
        {% include 'partials/header.html' %}
    </header>
    <content>
        <div class="container">
            {% block content %}
            <!-- Your Content Here -->
            
            {% endblock %}
        </div>
    </content>
    <footer>
        {% block footer %}
        {% include 'partials/footer.html' %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- JQuery dataTables Script -->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    {% block javascript %}
    {% endblock %}
</body>
</html>

tp2ppw/templates/partials/footer.html
<div class="footer">
    <h1 style="text-align:center">
        <small><em> Made with love by Kelompok Vale </em></small>
    </h1>
</div>

tp2ppw/templates/partials/header.html
<!-- Your Header Here -->
<!-- templates/lab_5/partials/header.html -->
<nav class="navbar navbar-default navbar-static-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav nav-right pull-right">
        
      
      </ul>
    </div>
</nav>